/* Generated By:JavaCC: Do not edit this line. CompiladorHell.java */
package parser;

import java.io.*;
import java.util.*;

import apoio.*;
import semantico.*;
import intermediario.*;
import intermediario2.*;
import destino.*;

public class CompiladorHell implements CompiladorHellConstants {

   public static Tabela tabela = new Tabela();

   public static void main(String args[]) throws ParseException {

      CompiladorHell analisador = null;
      try {
         analisador = new CompiladorHell(new FileInputStream(Config.nomeArquivoFonte));

                 // 1a passagem do Compilador - gera código intermediário
         ListaComandos listaComandos1aPassagem;
         listaComandos1aPassagem = CompiladorHell.inicio();
         System.out.println("Analise lexica e sintatica sem erros!");
                 System.out.println("\u005cn-----\u005cnTabela de simbolos: "+tabela);
         System.out.println("\u005cn-----\u005cnLista completa dos comandos apos a 1a passagem do compilador: "
                             +listaComandos1aPassagem);


                 // 2a passagem do Compilador - gera código intermediário mais proximo do assembler
                 PrimitivoListaComandos listaComandos2aPassagem;
                 listaComandos2aPassagem = listaComandos1aPassagem.geraListaPrimitivoComando();
                 System.out.println("\u005cn-----\u005cnLista completa dos comandos apos a 2a passagem do compilador: "
                                    +listaComandos2aPassagem);

                 // 3a passagem do Compilador - gera código destino - assembler (JVM do Java)
                 CodigoDestino codigoDestino = new CodigoDestino();
                 codigoDestino.geraCodigoAssembler(listaComandos2aPassagem);
         System.out.println("\u005cn-----\u005cnCodigo destino completo: \u005cn\u005cn" + codigoDestino);

      }
      catch(FileNotFoundException e) {
         System.out.println("Erro: arquivo nao encontrado");
      }
      catch(TokenMgrError e) {
         System.out.println("Erro lexico\u005cn" + e.getMessage());
      }
      catch(ParseException e) {
         System.out.println("Erro sintatico\u005cn" + e.getMessage());
      }
   }

/*
inicio        -> listaComandos() <EOF>
listaComandos -> (comando())* 
comando       -> 
	|comandoDeclaracoVariavel()
	|comandoAtribuicao()
	|comandoEntrada()
	|comandoPrinta()
	|comandoSe()
	|comandoTeste()
	|comandoLaco()
	|comandoLacoMultiplo()
	|comandoLacoMatrix()
*/
  static final public ListaComandos inicio() throws ParseException {
                           ListaComandos lista;
    lista = listaComandos();
    jj_consume_token(0);
           {if (true) return lista;}
    throw new Error("Missing return statement in function");
  }

  static final public ListaComandos listaComandos() throws ParseException {
                                  Comando com; ListaComandos lista = new ListaComandos();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case FOR:
      case IN:
      case OUT:
      case TEST:
      case FORMULTIPLE:
      case FORMATRIX:
      case TYPENUM:
      case TYPESTR:
      case TYPEBOOL:
      case VAR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      com = comando();
             if(com != null) // a declaracao de variaveis nao eh um comando: nao deve ser adicionada na lista
             {
                lista.add(com);
             }
    }
           {if (true) return lista;}
    throw new Error("Missing return statement in function");
  }

  static final public Comando comando() throws ParseException {
                     Comando com = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPENUM:
    case TYPESTR:
    case TYPEBOOL:
      comandoDeclaracaoVariavel();
      break;
    case VAR:
      com = comandoAtribuicao();
      break;
    case OUT:
      com = comandoPrinta();
      break;
    case IN:
      com = comandoPega();
      break;
    case IF:
      com = comandoSe();
      break;
    case TEST:
      com = comandoTeste();
      break;
    case FOR:
      com = comandoLaco();
      break;
    case FORMULTIPLE:
      com = comandoLacoMultiplo();
      break;
    case FORMATRIX:
      com = comandoLacoMatrix();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return com;}
    throw new Error("Missing return statement in function");
  }

/*
comandoDeclaracaoVariavel ->
    (
      <TYPENUM> <VAR> (<ATRIB> <NUM>)?
     ( <VIRG> <VAR> (<ATRIB> <NUM>)? )*
    | 
    <TYPESTR> <VAR> (<ATRIB> <STRING>)?
     ( <VIRG> <VAR> (<ATRIB> <STRING>)? )*
    | 
    <TYPEBOOL> <VAR> (<ATRIB> <BOOL>)?
     ( <VIRG>  <VAR> (<ATRIB> <BOOL>)? )*
    )
    <COMENT>	
*/
  static final public void comandoDeclaracaoVariavel() throws ParseException {
                                    Simbolo simb; Token var;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPENUM:
      jj_consume_token(TYPENUM);
      var = jj_consume_token(VAR);
                   simb = new Simbolo(var.image, Tipo.VAR_NUMERO);
                   if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
           else
                  CompiladorHell.tabela.inclui(simb);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        jj_consume_token(ATRIB);
        jj_consume_token(NUM);
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRG:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(VIRG);
        var = jj_consume_token(VAR);
                   simb = new Simbolo(var.image, Tipo.VAR_NUMERO);
                   if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
           else
                  CompiladorHell.tabela.inclui(simb);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ATRIB:
          jj_consume_token(ATRIB);
          jj_consume_token(NUM);
          break;
        default:
          jj_la1[4] = jj_gen;
          ;
        }
      }
      break;
    case TYPESTR:
      jj_consume_token(TYPESTR);
      var = jj_consume_token(VAR);
                   simb = new Simbolo(var.image, Tipo.VAR_STRING);
                   if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
           else
                  CompiladorHell.tabela.inclui(simb);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        jj_consume_token(ATRIB);
        jj_consume_token(STRING);
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRG:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_3;
        }
        jj_consume_token(VIRG);
        var = jj_consume_token(VAR);
                  simb = new Simbolo(var.image, Tipo.VAR_STRING);
                   if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
           else
                  CompiladorHell.tabela.inclui(simb);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ATRIB:
          jj_consume_token(ATRIB);
          jj_consume_token(STRING);
          break;
        default:
          jj_la1[7] = jj_gen;
          ;
        }
      }
      break;
    case TYPEBOOL:
      jj_consume_token(TYPEBOOL);
      var = jj_consume_token(VAR);
                  simb = new Simbolo(var.image, Tipo.VAR_BOOLEANO);
               CompiladorHell.tabela.inclui(simb);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        jj_consume_token(ATRIB);
        jj_consume_token(BOOL);
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRG:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        jj_consume_token(VIRG);
        var = jj_consume_token(VAR);
                  simb = new Simbolo(var.image, Tipo.VAR_BOOLEANO);
              CompiladorHell.tabela.inclui(simb);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ATRIB:
          jj_consume_token(ATRIB);
          jj_consume_token(BOOL);
          break;
        default:
          jj_la1[10] = jj_gen;
          ;
        }
      }
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(COMENT);
  }

/*
comandoAtribuicao ->  <VAR><ATRIB> exp <COMENT>
exp               ->  expLogica | expAritmetica | expString
*/
  static final public Comando comandoAtribuicao() throws ParseException {
                               ComandoAtribuicao atrib; Token var; Expressao expa;
    var = jj_consume_token(VAR);
    jj_consume_token(ATRIB);
    expa = exp();
      atrib = new ComandoAtribuicao(var.image, expa);
    jj_consume_token(COMENT);
        {if (true) return atrib;}
    throw new Error("Missing return statement in function");
  }

/*
comandoPrinta -> <OUT> <AP>
                 exp ((<VIRG>|<PT_VIRG>) exp)*
                 <FP> <COMENT>
*/
  static final public Comando comandoPrinta() throws ParseException {
                          ComandoPrinta printa; Expressao expa;
    jj_consume_token(OUT);
    try {
      jj_consume_token(AP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.COMENT, "abre parenteses");
                {if (true) return null;}
    }
    expa = exp();
          printa = new ComandoPrinta(expa);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
      case PT_VIRG:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        jj_consume_token(VIRG);
        break;
      case PT_VIRG:
        jj_consume_token(PT_VIRG);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expa = exp();
                  printa.addExpressao(expa);
    }
    try {
      jj_consume_token(FP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.COMENT, "fecha parenteses");
    }
    jj_consume_token(COMENT);
          {if (true) return printa;}
    throw new Error("Missing return statement in function");
  }

/*
comandoPega -> <IN><AP><VAR>(<VIRG><VAR>)*<FP><COMENT>
*/
  static final public Comando comandoPega() throws ParseException {
                         Token var; Pega pega = new Pega();
    jj_consume_token(IN);
    try {
      jj_consume_token(AP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.COMENT, "abre parenteses");
                {if (true) return null;}
    }
    var = jj_consume_token(VAR);
         pega.adicionaVariavel(var.image);
      if (!tabela.isExiste(var.image)) {
                        System.out.println("Variavel nao declarada: \u005c"" + var.image + "\u005c" na linha " +
                                                var.beginLine + ", coluna " + var.beginColumn);
                    System.exit(1);
      }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      jj_consume_token(VIRG);
      var = jj_consume_token(VAR);
           pega.adicionaVariavel(var.image);
        if (!tabela.isExiste(var.image)) {
                        System.out.println("Variavel nao declarada: \u005c"" + var.image + "\u005c" na linha " +
                                               var.beginLine + ", coluna " + var.beginColumn);
                    System.exit(1);
        }
    }
    try {
      jj_consume_token(FP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.COMENT, "fecha parenteses");
                {if (true) return null;}
    }
    jj_consume_token(COMENT);
         {if (true) return pega;}
    throw new Error("Missing return statement in function");
  }

/*
comandoSe -> <IF><AP> exp <FP>
             <ACH><COMENT>
             listaComandos <FCH>
             (<ELSE><ACH><COMENT>
             listaComandos <FCH>)?
*/
  static final public SeSenao comandoSe() throws ParseException {
                       SeSenao seSenao = new SeSenao(); Expressao expSeSenao;
                       ListaComandos listaComandosCondicaoVerdadeiro;
                       ListaComandos listaComandosCondicaoFalso;
    jj_consume_token(IF);
    jj_consume_token(AP);
    expSeSenao = exp();
    jj_consume_token(FP);
          seSenao.setExpSeSenao(expSeSenao);
    jj_consume_token(ACH);
    jj_consume_token(COMENT);
    listaComandosCondicaoVerdadeiro = listaComandos();
    jj_consume_token(FCH);
          seSenao.setListaComandosCondicaoVerdadeiro(listaComandosCondicaoVerdadeiro);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      jj_consume_token(ACH);
      jj_consume_token(COMENT);
      listaComandosCondicaoFalso = listaComandos();
             seSenao.setListaComandosCondicaoFalso(listaComandosCondicaoFalso);
      jj_consume_token(FCH);
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  {if (true) return seSenao;}
    throw new Error("Missing return statement in function");
  }

/*
comandoTeste() -> <TEST><ACH> (	blocoCondicional )+
            	  ( <OTHERWISE><ACH> <COMENT>
			        listaComandos()
			        <FCH> 
		          )? <FCH>

blocoCondicional -> <AP> exp <FP> <COMENT>
                    <ACH> listaComandos()
	                <FCH> (<BREAK>)? 
*/
  static final public Teste comandoTeste() throws ParseException {
                       Condicional cond; ListaComandos listaCom; Teste teste = new Teste();
    jj_consume_token(TEST);
    jj_consume_token(ACH);
    label_7:
    while (true) {
      cond = blocoCondicional();
                 teste.addCondicoes(cond);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AP:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OTHERWISE:
      jj_consume_token(OTHERWISE);
      jj_consume_token(ACH);
      jj_consume_token(COMENT);
      listaCom = listaComandos();
              teste.setOutroCaso(listaCom);
      jj_consume_token(FCH);
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(FCH);
         {if (true) return teste;}
    throw new Error("Missing return statement in function");
  }

  static final public Condicional blocoCondicional() throws ParseException {
                                Expressao e; ListaComandos listaCom;
                                Condicional cond = new Condicional();
    jj_consume_token(AP);
    e = exp();
         cond.setExpressao(e);
    jj_consume_token(FP);
    jj_consume_token(ACH);
    jj_consume_token(COMENT);
    listaCom = listaComandos();
     cond.setListaComandos(listaCom);
    jj_consume_token(FCH);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BREAK:
      jj_consume_token(BREAK);
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
          {if (true) return cond;}
    throw new Error("Missing return statement in function");
  }

/*
comandoLaco -> <FOR> <AP> (<TYPENUM>)? <VAR><ATRIB>
               exp <PT_VIRG>
               exp <PT_VIRG>
               comandoAtribuicao <FP>
               <ACH> <COMENT> listaComandos <FCH>
*/
  static final public Comando comandoLaco() throws ParseException {
                          Simbolo simb; Token var; Token tokenTipo = null;
                          Laco laco = new Laco();
                          Expressao expressaoAuxiliar = new Expressao();
                          ListaComandos listaAuxiliar = new ListaComandos();
    jj_consume_token(FOR);
    try {
      jj_consume_token(AP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "abre parenteses");
                {if (true) return null;}
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPENUM:
      tokenTipo = jj_consume_token(TYPENUM);
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    var = jj_consume_token(VAR);
          if(tokenTipo != null)
          {
             simb = new Simbolo(var.image, Tipo.VAR_NUMERO);
                 if(CompiladorHell.tabela.isExiste(var.image))
                         AnaliseSemantica.decaracaoRepetida(var);
         else
                 CompiladorHell.tabela.inclui(simb);
      }

      laco.setVarControle(var.image);
    jj_consume_token(ATRIB);
    expressaoAuxiliar = exp();
    jj_consume_token(PT_VIRG);
        laco.setExpressaoInicializacao(expressaoAuxiliar);
    expressaoAuxiliar = exp();
        laco.setExpressaoComparadora(expressaoAuxiliar);
    jj_consume_token(PT_VIRG);
    jj_consume_token(VAR);
    jj_consume_token(ATRIB);
    expressaoAuxiliar = exp();
        laco.setExpressaoIteracao(expressaoAuxiliar);
    try {
      jj_consume_token(FP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "fecha parenteses");
        {if (true) return null;}
    }
    jj_consume_token(ACH);
    jj_consume_token(COMENT);
    listaAuxiliar = listaComandos();
    jj_consume_token(FCH);
        laco.setListaComandos(listaAuxiliar);
      {if (true) return laco;}
    throw new Error("Missing return statement in function");
  }

/*
comandoLacoMultiplo -> <FOR_MULTIPLE> <AP> (TYPENUM)inicioLaco <FP>
                <ACH> <COMENT> listaComandos <FCH>
inicioLaco   -> <VAR> contLaco faixa
contLaco     -> <VIRG> <VAR> contLaco faixa <VIRG>
               | <PT_VIRG>
faixa -> exp <TO> exp
        (<STEP> exp)?
*/
  static final public Comando comandoLacoMultiplo() throws ParseException {
                                 Token tokenTipo = null;LacoMultiplo laco;ListaComandos listaAux;
    jj_consume_token(FORMULTIPLE);
    try {
      jj_consume_token(AP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "fecha parenteses");
        {if (true) return null;}
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPENUM:
      tokenTipo = jj_consume_token(TYPENUM);
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    laco = inicioLaco(tokenTipo);
    try {
      jj_consume_token(FP);
    } catch (ParseException e) {
                RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "fecha parenteses");
        {if (true) return null;}
    }
    jj_consume_token(ACH);
    jj_consume_token(COMENT);
    listaAux = listaComandos();
    jj_consume_token(FCH);
                laco.setListaComandos(listaAux);
                {if (true) return laco;}
    throw new Error("Missing return statement in function");
  }

  static final public LacoMultiplo inicioLaco(Token tokenTipo) throws ParseException {
                                            Simbolo simb; Token var;BlocoLacoMultiplo bloco;
    var = jj_consume_token(VAR);
          LacoMultiplo laco = new LacoMultiplo();
          bloco = new BlocoLacoMultiplo(var.image);
          laco.incluiBloco(bloco);

          if(tokenTipo!=null)
          {
                   simb = new Simbolo(var.image,Tipo.VAR_NUMERO);
                   if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
           else
                  CompiladorHell.tabela.inclui(simb);
      }
    contLaco(tokenTipo,laco);
    faixaLacoMultiplo(laco);
          {if (true) return laco;}
    throw new Error("Missing return statement in function");
  }

  static final public void contLaco(Token tokenTipo, LacoMultiplo laco) throws ParseException {
                                                     Simbolo simb; Token var;BlocoLacoMultiplo bloco;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VIRG:
      jj_consume_token(VIRG);
      var = jj_consume_token(VAR);
          bloco = new BlocoLacoMultiplo(var.image);
          laco.incluiBloco(bloco);
          if(tokenTipo!=null)
          {
                  simb = new Simbolo(var.image,Tipo.VAR_NUMERO);
                  if(CompiladorHell.tabela.isExiste(var.image))
                          AnaliseSemantica.decaracaoRepetida(var);
          else
                  CompiladorHell.tabela.inclui(simb);
      }
      contLaco(tokenTipo,laco);
      faixaLacoMultiplo(laco);
      jj_consume_token(VIRG);
      break;
    case PT_VIRG:
      jj_consume_token(PT_VIRG);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void faixaLacoMultiplo(LacoMultiplo laco) throws ParseException {
                                             Expressao expFrom, expTo,expStep; Item auxiliar;
          expFrom = new Expressao();
          expTo = new Expressao();
          expStep = new Expressao();
    expFrom = exp();
          expFrom.toString();
    jj_consume_token(TO);
    expTo = exp();
          expTo.toString();
          auxiliar = new Item(Tipo.CTE_NUMERO,"1");
          expStep.addInfixo(auxiliar);
          expStep.addPosfixo(auxiliar);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STEP:
      jj_consume_token(STEP);
      expStep = exp();
                expStep.toString();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
          laco.addFaixa(expFrom,expTo,expStep); //possui um contador interno para controle de insercao das faixas

  }

/*
comandoLacoMatrix -> <FORMATRIX> <AP> <VAR>
                    (<VIR> <VAR>)*
	                <PT_VIRG> faixa <FP>
	                <ACH> <COMENT>
	                listaComandos <FCH>	
faixa -> exp <TO> exp
        (<STEP> exp)?
*/
  static final public Comando comandoLacoMatrix() throws ParseException {
                               Simbolo simb; Token var; Token tipo = null;
                               LacoMatrix lacoMatrix = new LacoMatrix();
                               Expressao expressaoAuxiliar = new Expressao();
                               ListaComandos listaAuxiliar = new ListaComandos();
                               ArrayList<Expressao> expressao;
    jj_consume_token(FORMATRIX);
    try {
      jj_consume_token(AP);
    } catch (ParseException e) {
                   RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "fecha parenteses");
           {if (true) return null;}
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPENUM:
      tipo = jj_consume_token(TYPENUM);
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    var = jj_consume_token(VAR);
                  if(tipo!=null)
                  {
                    simb = new Simbolo(var.image,Tipo.VAR_NUMERO);
                    if(CompiladorHell.tabela.isExiste(var.image))
                           AnaliseSemantica.decaracaoRepetida(var);
            else
                   CompiladorHell.tabela.inclui(simb);
                  }
        lacoMatrix.setVariaveisControle(var.image);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_8;
      }
      jj_consume_token(VIRG);
      var = jj_consume_token(VAR);
                        if(tipo!=null)
                        {
                          simb = new Simbolo(var.image,Tipo.VAR_NUMERO);
                      if(CompiladorHell.tabela.isExiste(var.image))
                             AnaliseSemantica.decaracaoRepetida(var);
              else
                     CompiladorHell.tabela.inclui(simb);
                        }
          lacoMatrix.setVariaveisControle(var.image);
    }
    jj_consume_token(PT_VIRG);
    expressao = faixa();
            lacoMatrix.setExpressaoInicial(expressao.get(0));
            lacoMatrix.setExpressaoFinal(expressao.get(1));
            if(expressao.size() > 2)
                {
                  lacoMatrix.setExpressaoPasso(expressao.get(2));
                }
    try {
      jj_consume_token(FP);
    } catch (ParseException e) {
                  RecuperacaoErro.recuperaErroPanico(CompiladorHellConstants.ACH, "fecha parenteses");
          {if (true) return null;}
    }
    jj_consume_token(ACH);
    jj_consume_token(COMENT);
    listaAuxiliar = listaComandos();
        lacoMatrix.setListaComandos(listaAuxiliar);
    jj_consume_token(FCH);
        {if (true) return lacoMatrix;}
    throw new Error("Missing return statement in function");
  }

/*
faixa -> exp <TO> exp
        (<STEP> exp)?
*/
  static final public ArrayList<Expressao> faixa() throws ParseException {
                               ArrayList<Expressao> listaExpressoes = new ArrayList<Expressao>();
                               Expressao e;
    e = exp();
                listaExpressoes.add(e);
    jj_consume_token(TO);
    e = exp();
               listaExpressoes.add(e);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STEP:
      jj_consume_token(STEP);
      e = exp();
                  listaExpressoes.add(e);
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
      {if (true) return listaExpressoes;}
    throw new Error("Missing return statement in function");
  }

/*
exp           -> expOr   ( <CONCAT>  expOr )*
expOr         -> expAnd   ( <OR>  expAnd )*
expAnd        -> expNot   ( <AND> expNot )*
expNot        -> ( <NOT> )* expRelacional
expRelacional -> expAdit  ( <MAIOR>   expAdit | <MENOR>   expAdit 
                          | <MAIOR_I> expAdit | <MENOR_I> expAdit |
                          | <IGUAL>   expAdit | <DIF>     expAdit )*
expAdit       -> expMult  ( <ADD>  expMult | <SUB> expMult  )*
expMult       -> expPot   ( <MULT> expPot  | <DIV> expPot )*
expPot        -> expToken ( <POT> expPot )?
expToken      -> <NUM> | <ADD><NUM> | <SUB><NUM> | <VAR> | <BOOL> | <STRING> 
                 | <AP> exp <FP>
*/
  static final public Expressao exp() throws ParseException {
                   Expressao e = new Expressao();
    exp0(e);
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  static final public void exp0(Expressao e) throws ParseException {
                           Item item; Token t;
    expOr(e);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONCAT:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_9;
      }
      t = jj_consume_token(CONCAT);
        item = new Item(Tipo.OPERADOR, t.image);
        e.addInfixo(item);
      expOr(e);
        e.addPosfixo(item);
    }
  }

  static final public void expOr(Expressao e) throws ParseException {
                           Item item; Token t;
    expAnd(e);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_10;
      }
      t = jj_consume_token(OR);
        item = new Item(Tipo.OPERADOR, t.image);
        e.addInfixo(item);
      expAnd(e);
        e.addPosfixo(item);
    }
  }

  static final public void expAnd(Expressao e) throws ParseException {
                            Item item; Token t;
    expAnds(e);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_11;
      }
      t = jj_consume_token(AND);
          item = new Item(Tipo.OPERADOR, t.image);
          e.addInfixo(item);
      expAnds(e);
        e.addPosfixo(item);
    }
  }

  static final public void expAnds(Expressao e) throws ParseException {
                             Item item; Token t;
    expNot(e);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ANDS:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_12;
      }
      t = jj_consume_token(ANDS);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
      expNot(e);
        e.addPosfixo(item);
    }
  }

  static final public void expNot(Expressao e) throws ParseException {
                            Item item = null; Token t; int cont = 0;
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_13;
      }
      t = jj_consume_token(NOT);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
               cont++;
    }
    expRelacional(e);
        while(cont-- > 0)
           e.addPosfixo(item);
  }

  static final public void expRelacional(Expressao e) throws ParseException {
                                   Item item; Token t;
    expAdit(e);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIOR:
      case MENOR:
      case MAIOR_I:
      case MENOR_I:
      case IGUAL:
      case DIF:
        ;
        break;
      default:
        jj_la1[31] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIOR:
        t = jj_consume_token(MAIOR);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      case MENOR:
        t = jj_consume_token(MENOR);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      case MAIOR_I:
        t = jj_consume_token(MAIOR_I);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      case MENOR_I:
        t = jj_consume_token(MENOR_I);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      case IGUAL:
        t = jj_consume_token(IGUAL);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      case DIF:
        t = jj_consume_token(DIF);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expAdit(e);
           e.addPosfixo(item);
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void expAdit(Expressao e) throws ParseException {
                             Item item; Token t;
    expMult(e);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
      case SUB:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
        t = jj_consume_token(ADD);
                 item = new Item(Tipo.OPERADOR, t.image);
                 e.addInfixo(item);
        expMult(e);
             e.addPosfixo(item);
        break;
      case SUB:
        t = jj_consume_token(SUB);
                 item = new Item(Tipo.OPERADOR, t.image);
                 e.addInfixo(item);
        expMult(e);
             e.addPosfixo(item);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void expMult(Expressao e) throws ParseException {
                             Item item; Token t;
    expPot(e);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
      case DIV:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
        t = jj_consume_token(MULT);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expPot(e);
           e.addPosfixo(item);
        break;
      case DIV:
        t = jj_consume_token(DIV);
               item = new Item(Tipo.OPERADOR, t.image);
               e.addInfixo(item);
        expPot(e);
           e.addPosfixo(item);
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void expPot(Expressao e) throws ParseException {
                            Item item; Token t;
    expToken(e);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POT:
      t = jj_consume_token(POT);
                item = new Item(Tipo.OPERADOR, t.image);
            e.addInfixo(item);
      expPot(e);
            e.addPosfixo(item);
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
  }

  static final public void expToken(Expressao e) throws ParseException {
                             Item item; Token t; String tConcatenada;Tipo tipo;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
      t = jj_consume_token(NUM);
         item = new Item(Tipo.CTE_NUMERO, t.image);
         e.addPosfixo(item);
         e.addInfixo(item);
      break;
    case ADD:
      t = jj_consume_token(ADD);
        tConcatenada = t.image;
      t = jj_consume_token(NUM);
         tConcatenada = tConcatenada + t.image;
         item = new Item(Tipo.CTE_NUMERO, tConcatenada);
         e.addPosfixo(item);
         e.addInfixo(item);
      break;
    case SUB:
      t = jj_consume_token(SUB);
        tConcatenada = t.image;
      t = jj_consume_token(NUM);
         tConcatenada = tConcatenada + t.image;
         item = new Item(Tipo.CTE_NUMERO, tConcatenada);
         e.addPosfixo(item);
         e.addInfixo(item);
      break;
    case VAR:
      t = jj_consume_token(VAR);
              if (!tabela.isExiste(t.image)) {
                         System.out.println("Variavel nao declarada: \u005c"" + t.image + "\u005c" na linha " +
                                                t.beginLine + ", coluna " + t.beginColumn);
                         System.exit(1);
          }
          tipo = tabela.consultaTipo(t.image);
          item = new Item(tipo,t.image);
          e.addPosfixo(item);
          e.addInfixo(item);
      break;
    case BOOL:
      t = jj_consume_token(BOOL);
        item = new Item(Tipo.CTE_BOOLEANO, t.image);
        e.addPosfixo(item);
        e.addInfixo(item);
      break;
    case STRING:
      t = jj_consume_token(STRING);
        item = new Item(Tipo.CTE_STRING, t.image);
        e.addPosfixo(item);
        e.addInfixo(item);
      break;
    case AP:
      t = jj_consume_token(AP);
        item = new Item(Tipo.PARENTESES, t.image);
        e.addInfixo(item);
      exp0(e);
      t = jj_consume_token(FP);
        item = new Item(Tipo.PARENTESES, t.image);
        e.addInfixo(item);
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorHellTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[39];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x7a000000,0x7a000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000000,0x0,0x0,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000,0x400000,0x200000,0x1000000,0x800000,0x1f8000,0x1f8000,0x300,0x300,0xc00,0xc00,0x1000,0x300,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x47006,0x47006,0x800,0x20,0x800,0x800,0x20,0x800,0x800,0x20,0x800,0x7000,0x60,0x60,0x20,0x0,0x80,0x1,0x0,0x1000,0x1000,0x60,0x10,0x1000,0x20,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x78080,};
   }

  /** Constructor with InputStream. */
  public CompiladorHell(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CompiladorHell(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorHellTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CompiladorHell(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorHellTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CompiladorHell(CompiladorHellTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorHellTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 39; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
